//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumoServiciosWeb.TariffComputerLocal {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TariffComputerLocal.TariffComputerWSSoap")]
    public interface TariffComputerWSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryParkingOperation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string QueryParkingOperation(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryParkingOperation", ReplyAction="*")]
        System.Threading.Tasks.Task<string> QueryParkingOperationAsync(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryParkingOperationJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string QueryParkingOperationJSON(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryParkingOperationJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<string> QueryParkingOperationJSONAsync(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryParkingOperationWithTimeSteps", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string QueryParkingOperationWithTimeSteps(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryParkingOperationWithTimeSteps", ReplyAction="*")]
        System.Threading.Tasks.Task<string> QueryParkingOperationWithTimeStepsAsync(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryParkingOperationWithTimeStepsJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string QueryParkingOperationWithTimeStepsJSON(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryParkingOperationWithTimeStepsJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<string> QueryParkingOperationWithTimeStepsJSONAsync(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryParkingOperationWithAmountSteps", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string QueryParkingOperationWithAmountSteps(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryParkingOperationWithAmountSteps", ReplyAction="*")]
        System.Threading.Tasks.Task<string> QueryParkingOperationWithAmountStepsAsync(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryParkingOperationWithAmountStepsJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string QueryParkingOperationWithAmountStepsJSON(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryParkingOperationWithAmountStepsJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<string> QueryParkingOperationWithAmountStepsJSONAsync(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryUnParkingOperation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string QueryUnParkingOperation(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryUnParkingOperation", ReplyAction="*")]
        System.Threading.Tasks.Task<string> QueryUnParkingOperationAsync(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryUnParkingOperationJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string QueryUnParkingOperationJSON(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryUnParkingOperationJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<string> QueryUnParkingOperationJSONAsync(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertExternalParkingOperationInstallationTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertExternalParkingOperationInstallationTime(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertExternalParkingOperationInstallationTime", ReplyAction="*")]
        System.Threading.Tasks.Task<string> InsertExternalParkingOperationInstallationTimeAsync(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertExternalParkingOperationInstallationTimeJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertExternalParkingOperationInstallationTimeJSON(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertExternalParkingOperationInstallationTimeJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<string> InsertExternalParkingOperationInstallationTimeJSONAsync(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertExternalParkingOperationUTCTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertExternalParkingOperationUTCTime(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertExternalParkingOperationUTCTime", ReplyAction="*")]
        System.Threading.Tasks.Task<string> InsertExternalParkingOperationUTCTimeAsync(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertExternalParkingOperationUTCTimeJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertExternalParkingOperationUTCTimeJSON(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertExternalParkingOperationUTCTimeJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<string> InsertExternalParkingOperationUTCTimeJSONAsync(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertExternalUnParkingOperationInstallationTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertExternalUnParkingOperationInstallationTime(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertExternalUnParkingOperationInstallationTime", ReplyAction="*")]
        System.Threading.Tasks.Task<string> InsertExternalUnParkingOperationInstallationTimeAsync(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertExternalUnParkingOperationInstallationTimeJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertExternalUnParkingOperationInstallationTimeJSON(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertExternalUnParkingOperationInstallationTimeJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<string> InsertExternalUnParkingOperationInstallationTimeJSONAsync(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertExternalUnParkingOperationUTCTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertExternalUnParkingOperationUTCTime(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertExternalUnParkingOperationUTCTime", ReplyAction="*")]
        System.Threading.Tasks.Task<string> InsertExternalUnParkingOperationUTCTimeAsync(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertExternalUnParkingOperationUTCTimeJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertExternalUnParkingOperationUTCTimeJSON(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertExternalUnParkingOperationUTCTimeJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<string> InsertExternalUnParkingOperationUTCTimeJSONAsync(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertExternalParkingOperationGtechna", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertExternalParkingOperationGtechna(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertExternalParkingOperationGtechna", ReplyAction="*")]
        System.Threading.Tasks.Task<string> InsertExternalParkingOperationGtechnaAsync(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertExternalParkingOperationGtechnaJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertExternalParkingOperationGtechnaJSON(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertExternalParkingOperationGtechnaJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<string> InsertExternalParkingOperationGtechnaJSONAsync(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertExternalParkingOperationParkingmeter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertExternalParkingOperationParkingmeter(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertExternalParkingOperationParkingmeter", ReplyAction="*")]
        System.Threading.Tasks.Task<string> InsertExternalParkingOperationParkingmeterAsync(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertExternalParkingOperationParkingmeterJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertExternalParkingOperationParkingmeterJSON(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertExternalParkingOperationParkingmeterJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<string> InsertExternalParkingOperationParkingmeterJSONAsync(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryPlateLastParkingOperation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string QueryPlateLastParkingOperation(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryPlateLastParkingOperation", ReplyAction="*")]
        System.Threading.Tasks.Task<string> QueryPlateLastParkingOperationAsync(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryPlateLastParkingOperationJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string QueryPlateLastParkingOperationJSON(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryPlateLastParkingOperationJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<string> QueryPlateLastParkingOperationJSONAsync(string jsonIn);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TariffComputerWSSoapChannel : ConsumoServiciosWeb.TariffComputerLocal.TariffComputerWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TariffComputerWSSoapClient : System.ServiceModel.ClientBase<ConsumoServiciosWeb.TariffComputerLocal.TariffComputerWSSoap>, ConsumoServiciosWeb.TariffComputerLocal.TariffComputerWSSoap {
        
        public TariffComputerWSSoapClient() {
        }
        
        public TariffComputerWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TariffComputerWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TariffComputerWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TariffComputerWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string QueryParkingOperation(string xmlIn) {
            return base.Channel.QueryParkingOperation(xmlIn);
        }
        
        public System.Threading.Tasks.Task<string> QueryParkingOperationAsync(string xmlIn) {
            return base.Channel.QueryParkingOperationAsync(xmlIn);
        }
        
        public string QueryParkingOperationJSON(string jsonIn) {
            return base.Channel.QueryParkingOperationJSON(jsonIn);
        }
        
        public System.Threading.Tasks.Task<string> QueryParkingOperationJSONAsync(string jsonIn) {
            return base.Channel.QueryParkingOperationJSONAsync(jsonIn);
        }
        
        public string QueryParkingOperationWithTimeSteps(string xmlIn) {
            return base.Channel.QueryParkingOperationWithTimeSteps(xmlIn);
        }
        
        public System.Threading.Tasks.Task<string> QueryParkingOperationWithTimeStepsAsync(string xmlIn) {
            return base.Channel.QueryParkingOperationWithTimeStepsAsync(xmlIn);
        }
        
        public string QueryParkingOperationWithTimeStepsJSON(string jsonIn) {
            return base.Channel.QueryParkingOperationWithTimeStepsJSON(jsonIn);
        }
        
        public System.Threading.Tasks.Task<string> QueryParkingOperationWithTimeStepsJSONAsync(string jsonIn) {
            return base.Channel.QueryParkingOperationWithTimeStepsJSONAsync(jsonIn);
        }
        
        public string QueryParkingOperationWithAmountSteps(string xmlIn) {
            return base.Channel.QueryParkingOperationWithAmountSteps(xmlIn);
        }
        
        public System.Threading.Tasks.Task<string> QueryParkingOperationWithAmountStepsAsync(string xmlIn) {
            return base.Channel.QueryParkingOperationWithAmountStepsAsync(xmlIn);
        }
        
        public string QueryParkingOperationWithAmountStepsJSON(string jsonIn) {
            return base.Channel.QueryParkingOperationWithAmountStepsJSON(jsonIn);
        }
        
        public System.Threading.Tasks.Task<string> QueryParkingOperationWithAmountStepsJSONAsync(string jsonIn) {
            return base.Channel.QueryParkingOperationWithAmountStepsJSONAsync(jsonIn);
        }
        
        public string QueryUnParkingOperation(string xmlIn) {
            return base.Channel.QueryUnParkingOperation(xmlIn);
        }
        
        public System.Threading.Tasks.Task<string> QueryUnParkingOperationAsync(string xmlIn) {
            return base.Channel.QueryUnParkingOperationAsync(xmlIn);
        }
        
        public string QueryUnParkingOperationJSON(string jsonIn) {
            return base.Channel.QueryUnParkingOperationJSON(jsonIn);
        }
        
        public System.Threading.Tasks.Task<string> QueryUnParkingOperationJSONAsync(string jsonIn) {
            return base.Channel.QueryUnParkingOperationJSONAsync(jsonIn);
        }
        
        public string InsertExternalParkingOperationInstallationTime(string xmlIn) {
            return base.Channel.InsertExternalParkingOperationInstallationTime(xmlIn);
        }
        
        public System.Threading.Tasks.Task<string> InsertExternalParkingOperationInstallationTimeAsync(string xmlIn) {
            return base.Channel.InsertExternalParkingOperationInstallationTimeAsync(xmlIn);
        }
        
        public string InsertExternalParkingOperationInstallationTimeJSON(string jsonIn) {
            return base.Channel.InsertExternalParkingOperationInstallationTimeJSON(jsonIn);
        }
        
        public System.Threading.Tasks.Task<string> InsertExternalParkingOperationInstallationTimeJSONAsync(string jsonIn) {
            return base.Channel.InsertExternalParkingOperationInstallationTimeJSONAsync(jsonIn);
        }
        
        public string InsertExternalParkingOperationUTCTime(string xmlIn) {
            return base.Channel.InsertExternalParkingOperationUTCTime(xmlIn);
        }
        
        public System.Threading.Tasks.Task<string> InsertExternalParkingOperationUTCTimeAsync(string xmlIn) {
            return base.Channel.InsertExternalParkingOperationUTCTimeAsync(xmlIn);
        }
        
        public string InsertExternalParkingOperationUTCTimeJSON(string jsonIn) {
            return base.Channel.InsertExternalParkingOperationUTCTimeJSON(jsonIn);
        }
        
        public System.Threading.Tasks.Task<string> InsertExternalParkingOperationUTCTimeJSONAsync(string jsonIn) {
            return base.Channel.InsertExternalParkingOperationUTCTimeJSONAsync(jsonIn);
        }
        
        public string InsertExternalUnParkingOperationInstallationTime(string xmlIn) {
            return base.Channel.InsertExternalUnParkingOperationInstallationTime(xmlIn);
        }
        
        public System.Threading.Tasks.Task<string> InsertExternalUnParkingOperationInstallationTimeAsync(string xmlIn) {
            return base.Channel.InsertExternalUnParkingOperationInstallationTimeAsync(xmlIn);
        }
        
        public string InsertExternalUnParkingOperationInstallationTimeJSON(string jsonIn) {
            return base.Channel.InsertExternalUnParkingOperationInstallationTimeJSON(jsonIn);
        }
        
        public System.Threading.Tasks.Task<string> InsertExternalUnParkingOperationInstallationTimeJSONAsync(string jsonIn) {
            return base.Channel.InsertExternalUnParkingOperationInstallationTimeJSONAsync(jsonIn);
        }
        
        public string InsertExternalUnParkingOperationUTCTime(string xmlIn) {
            return base.Channel.InsertExternalUnParkingOperationUTCTime(xmlIn);
        }
        
        public System.Threading.Tasks.Task<string> InsertExternalUnParkingOperationUTCTimeAsync(string xmlIn) {
            return base.Channel.InsertExternalUnParkingOperationUTCTimeAsync(xmlIn);
        }
        
        public string InsertExternalUnParkingOperationUTCTimeJSON(string jsonIn) {
            return base.Channel.InsertExternalUnParkingOperationUTCTimeJSON(jsonIn);
        }
        
        public System.Threading.Tasks.Task<string> InsertExternalUnParkingOperationUTCTimeJSONAsync(string jsonIn) {
            return base.Channel.InsertExternalUnParkingOperationUTCTimeJSONAsync(jsonIn);
        }
        
        public string InsertExternalParkingOperationGtechna(string xmlIn) {
            return base.Channel.InsertExternalParkingOperationGtechna(xmlIn);
        }
        
        public System.Threading.Tasks.Task<string> InsertExternalParkingOperationGtechnaAsync(string xmlIn) {
            return base.Channel.InsertExternalParkingOperationGtechnaAsync(xmlIn);
        }
        
        public string InsertExternalParkingOperationGtechnaJSON(string jsonIn) {
            return base.Channel.InsertExternalParkingOperationGtechnaJSON(jsonIn);
        }
        
        public System.Threading.Tasks.Task<string> InsertExternalParkingOperationGtechnaJSONAsync(string jsonIn) {
            return base.Channel.InsertExternalParkingOperationGtechnaJSONAsync(jsonIn);
        }
        
        public string InsertExternalParkingOperationParkingmeter(string xmlIn) {
            return base.Channel.InsertExternalParkingOperationParkingmeter(xmlIn);
        }
        
        public System.Threading.Tasks.Task<string> InsertExternalParkingOperationParkingmeterAsync(string xmlIn) {
            return base.Channel.InsertExternalParkingOperationParkingmeterAsync(xmlIn);
        }
        
        public string InsertExternalParkingOperationParkingmeterJSON(string jsonIn) {
            return base.Channel.InsertExternalParkingOperationParkingmeterJSON(jsonIn);
        }
        
        public System.Threading.Tasks.Task<string> InsertExternalParkingOperationParkingmeterJSONAsync(string jsonIn) {
            return base.Channel.InsertExternalParkingOperationParkingmeterJSONAsync(jsonIn);
        }
        
        public string QueryPlateLastParkingOperation(string xmlIn) {
            return base.Channel.QueryPlateLastParkingOperation(xmlIn);
        }
        
        public System.Threading.Tasks.Task<string> QueryPlateLastParkingOperationAsync(string xmlIn) {
            return base.Channel.QueryPlateLastParkingOperationAsync(xmlIn);
        }
        
        public string QueryPlateLastParkingOperationJSON(string jsonIn) {
            return base.Channel.QueryPlateLastParkingOperationJSON(jsonIn);
        }
        
        public System.Threading.Tasks.Task<string> QueryPlateLastParkingOperationJSONAsync(string jsonIn) {
            return base.Channel.QueryPlateLastParkingOperationJSONAsync(jsonIn);
        }
    }
}
