//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumoServiciosWeb.PxEndpointWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsolaSoapHeader", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ConsolaSoapHeader : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdContrataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LocalTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumSerieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdContrata {
            get {
                return this.IdContrataField;
            }
            set {
                if ((this.IdContrataField.Equals(value) != true)) {
                    this.IdContrataField = value;
                    this.RaisePropertyChanged("IdContrata");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.IdUsuarioField, value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LocalTime {
            get {
                return this.LocalTimeField;
            }
            set {
                if ((this.LocalTimeField.Equals(value) != true)) {
                    this.LocalTimeField = value;
                    this.RaisePropertyChanged("LocalTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomUsuario {
            get {
                return this.NomUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NomUsuarioField, value) != true)) {
                    this.NomUsuarioField = value;
                    this.RaisePropertyChanged("NomUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumSerie {
            get {
                return this.NumSerieField;
            }
            set {
                if ((object.ReferenceEquals(this.NumSerieField, value) != true)) {
                    this.NumSerieField = value;
                    this.RaisePropertyChanged("NumSerie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PxEndpointWCF.IEndpoints")]
    public interface IEndpoints {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje rdPConfirmUnParkingOperationRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/rdPConfirmUnParkingOperation", ReplyAction="http://tempuri.org/rdPConfirmUnParkingOperation")]
        ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmUnParkingOperationResponse rdPConfirmUnParkingOperation(ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmUnParkingOperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/rdPConfirmUnParkingOperation", ReplyAction="http://tempuri.org/rdPConfirmUnParkingOperation")]
        System.Threading.Tasks.Task<ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmUnParkingOperationResponse> rdPConfirmUnParkingOperationAsync(ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmUnParkingOperationRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje rdPQueryFinePaymentQuantityRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/rdPQueryFinePaymentQuantity", ReplyAction="http://tempuri.org/rdPQueryFinePaymentQuantity")]
        ConsumoServiciosWeb.PxEndpointWCF.rdPQueryFinePaymentQuantityResponse rdPQueryFinePaymentQuantity(ConsumoServiciosWeb.PxEndpointWCF.rdPQueryFinePaymentQuantityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/rdPQueryFinePaymentQuantity", ReplyAction="http://tempuri.org/rdPQueryFinePaymentQuantity")]
        System.Threading.Tasks.Task<ConsumoServiciosWeb.PxEndpointWCF.rdPQueryFinePaymentQuantityResponse> rdPQueryFinePaymentQuantityAsync(ConsumoServiciosWeb.PxEndpointWCF.rdPQueryFinePaymentQuantityRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje rdPQueryListOfFinesRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/rdPQueryListOfFines", ReplyAction="http://tempuri.org/rdPQueryListOfFines")]
        ConsumoServiciosWeb.PxEndpointWCF.rdPQueryListOfFinesResponse rdPQueryListOfFines(ConsumoServiciosWeb.PxEndpointWCF.rdPQueryListOfFinesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/rdPQueryListOfFines", ReplyAction="http://tempuri.org/rdPQueryListOfFines")]
        System.Threading.Tasks.Task<ConsumoServiciosWeb.PxEndpointWCF.rdPQueryListOfFinesResponse> rdPQueryListOfFinesAsync(ConsumoServiciosWeb.PxEndpointWCF.rdPQueryListOfFinesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje rdPConfirmFinePaymentRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/rdPConfirmFinePayment", ReplyAction="http://tempuri.org/rdPConfirmFinePayment")]
        ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmFinePaymentResponse rdPConfirmFinePayment(ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmFinePaymentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/rdPConfirmFinePayment", ReplyAction="http://tempuri.org/rdPConfirmFinePayment")]
        System.Threading.Tasks.Task<ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmFinePaymentResponse> rdPConfirmFinePaymentAsync(ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmFinePaymentRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje rdPNotifyAlarmRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/rdPNotifyAlarm", ReplyAction="http://tempuri.org/rdPNotifyAlarm")]
        ConsumoServiciosWeb.PxEndpointWCF.rdPNotifyAlarmResponse rdPNotifyAlarm(ConsumoServiciosWeb.PxEndpointWCF.rdPNotifyAlarmRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/rdPNotifyAlarm", ReplyAction="http://tempuri.org/rdPNotifyAlarm")]
        System.Threading.Tasks.Task<ConsumoServiciosWeb.PxEndpointWCF.rdPNotifyAlarmResponse> rdPNotifyAlarmAsync(ConsumoServiciosWeb.PxEndpointWCF.rdPNotifyAlarmRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje rdPNotifyCollectionRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/rdPNotifyCollection", ReplyAction="http://tempuri.org/rdPNotifyCollection")]
        ConsumoServiciosWeb.PxEndpointWCF.rdPNotifyCollectionResponse rdPNotifyCollection(ConsumoServiciosWeb.PxEndpointWCF.rdPNotifyCollectionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/rdPNotifyCollection", ReplyAction="http://tempuri.org/rdPNotifyCollection")]
        System.Threading.Tasks.Task<ConsumoServiciosWeb.PxEndpointWCF.rdPNotifyCollectionResponse> rdPNotifyCollectionAsync(ConsumoServiciosWeb.PxEndpointWCF.rdPNotifyCollectionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje rdPConfirmParkingOperationRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/rdPConfirmParkingOperation", ReplyAction="http://tempuri.org/rdPConfirmParkingOperation")]
        ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmParkingOperationResponse rdPConfirmParkingOperation(ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmParkingOperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/rdPConfirmParkingOperation", ReplyAction="http://tempuri.org/rdPConfirmParkingOperation")]
        System.Threading.Tasks.Task<ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmParkingOperationResponse> rdPConfirmParkingOperationAsync(ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmParkingOperationRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje rdPCancelParkingOperationRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/rdPCancelParkingOperation", ReplyAction="http://tempuri.org/rdPCancelParkingOperation")]
        ConsumoServiciosWeb.PxEndpointWCF.rdPCancelParkingOperationResponse rdPCancelParkingOperation(ConsumoServiciosWeb.PxEndpointWCF.rdPCancelParkingOperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/rdPCancelParkingOperation", ReplyAction="http://tempuri.org/rdPCancelParkingOperation")]
        System.Threading.Tasks.Task<ConsumoServiciosWeb.PxEndpointWCF.rdPCancelParkingOperationResponse> rdPCancelParkingOperationAsync(ConsumoServiciosWeb.PxEndpointWCF.rdPCancelParkingOperationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rdPConfirmUnParkingOperation", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class rdPConfirmUnParkingOperationRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public ConsumoServiciosWeb.PxEndpointWCF.ConsolaSoapHeader ConsolaSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string xmlIn;
        
        public rdPConfirmUnParkingOperationRequest() {
        }
        
        public rdPConfirmUnParkingOperationRequest(ConsumoServiciosWeb.PxEndpointWCF.ConsolaSoapHeader ConsolaSoapHeader, string xmlIn) {
            this.ConsolaSoapHeader = ConsolaSoapHeader;
            this.xmlIn = xmlIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rdPConfirmUnParkingOperationResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class rdPConfirmUnParkingOperationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string rdPConfirmUnParkingOperationResult;
        
        public rdPConfirmUnParkingOperationResponse() {
        }
        
        public rdPConfirmUnParkingOperationResponse(string rdPConfirmUnParkingOperationResult) {
            this.rdPConfirmUnParkingOperationResult = rdPConfirmUnParkingOperationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rdPQueryFinePaymentQuantity", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class rdPQueryFinePaymentQuantityRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public ConsumoServiciosWeb.PxEndpointWCF.ConsolaSoapHeader ConsolaSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string xmlIn;
        
        public rdPQueryFinePaymentQuantityRequest() {
        }
        
        public rdPQueryFinePaymentQuantityRequest(ConsumoServiciosWeb.PxEndpointWCF.ConsolaSoapHeader ConsolaSoapHeader, string xmlIn) {
            this.ConsolaSoapHeader = ConsolaSoapHeader;
            this.xmlIn = xmlIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rdPQueryFinePaymentQuantityResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class rdPQueryFinePaymentQuantityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string rdPQueryFinePaymentQuantityResult;
        
        public rdPQueryFinePaymentQuantityResponse() {
        }
        
        public rdPQueryFinePaymentQuantityResponse(string rdPQueryFinePaymentQuantityResult) {
            this.rdPQueryFinePaymentQuantityResult = rdPQueryFinePaymentQuantityResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rdPQueryListOfFines", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class rdPQueryListOfFinesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public ConsumoServiciosWeb.PxEndpointWCF.ConsolaSoapHeader ConsolaSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string xmlIn;
        
        public rdPQueryListOfFinesRequest() {
        }
        
        public rdPQueryListOfFinesRequest(ConsumoServiciosWeb.PxEndpointWCF.ConsolaSoapHeader ConsolaSoapHeader, string xmlIn) {
            this.ConsolaSoapHeader = ConsolaSoapHeader;
            this.xmlIn = xmlIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rdPQueryListOfFinesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class rdPQueryListOfFinesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string rdPQueryListOfFinesResult;
        
        public rdPQueryListOfFinesResponse() {
        }
        
        public rdPQueryListOfFinesResponse(string rdPQueryListOfFinesResult) {
            this.rdPQueryListOfFinesResult = rdPQueryListOfFinesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rdPConfirmFinePayment", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class rdPConfirmFinePaymentRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public ConsumoServiciosWeb.PxEndpointWCF.ConsolaSoapHeader ConsolaSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string xmlIn;
        
        public rdPConfirmFinePaymentRequest() {
        }
        
        public rdPConfirmFinePaymentRequest(ConsumoServiciosWeb.PxEndpointWCF.ConsolaSoapHeader ConsolaSoapHeader, string xmlIn) {
            this.ConsolaSoapHeader = ConsolaSoapHeader;
            this.xmlIn = xmlIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rdPConfirmFinePaymentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class rdPConfirmFinePaymentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string rdPConfirmFinePaymentResult;
        
        public rdPConfirmFinePaymentResponse() {
        }
        
        public rdPConfirmFinePaymentResponse(string rdPConfirmFinePaymentResult) {
            this.rdPConfirmFinePaymentResult = rdPConfirmFinePaymentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rdPNotifyAlarm", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class rdPNotifyAlarmRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public ConsumoServiciosWeb.PxEndpointWCF.ConsolaSoapHeader ConsolaSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string xmlIn;
        
        public rdPNotifyAlarmRequest() {
        }
        
        public rdPNotifyAlarmRequest(ConsumoServiciosWeb.PxEndpointWCF.ConsolaSoapHeader ConsolaSoapHeader, string xmlIn) {
            this.ConsolaSoapHeader = ConsolaSoapHeader;
            this.xmlIn = xmlIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rdPNotifyAlarmResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class rdPNotifyAlarmResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string rdPNotifyAlarmResult;
        
        public rdPNotifyAlarmResponse() {
        }
        
        public rdPNotifyAlarmResponse(string rdPNotifyAlarmResult) {
            this.rdPNotifyAlarmResult = rdPNotifyAlarmResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rdPNotifyCollection", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class rdPNotifyCollectionRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public ConsumoServiciosWeb.PxEndpointWCF.ConsolaSoapHeader ConsolaSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string xmlIn;
        
        public rdPNotifyCollectionRequest() {
        }
        
        public rdPNotifyCollectionRequest(ConsumoServiciosWeb.PxEndpointWCF.ConsolaSoapHeader ConsolaSoapHeader, string xmlIn) {
            this.ConsolaSoapHeader = ConsolaSoapHeader;
            this.xmlIn = xmlIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rdPNotifyCollectionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class rdPNotifyCollectionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string rdPNotifyCollectionResult;
        
        public rdPNotifyCollectionResponse() {
        }
        
        public rdPNotifyCollectionResponse(string rdPNotifyCollectionResult) {
            this.rdPNotifyCollectionResult = rdPNotifyCollectionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rdPConfirmParkingOperation", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class rdPConfirmParkingOperationRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public ConsumoServiciosWeb.PxEndpointWCF.ConsolaSoapHeader ConsolaSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string xmlIn;
        
        public rdPConfirmParkingOperationRequest() {
        }
        
        public rdPConfirmParkingOperationRequest(ConsumoServiciosWeb.PxEndpointWCF.ConsolaSoapHeader ConsolaSoapHeader, string xmlIn) {
            this.ConsolaSoapHeader = ConsolaSoapHeader;
            this.xmlIn = xmlIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rdPConfirmParkingOperationResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class rdPConfirmParkingOperationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string rdPConfirmParkingOperationResult;
        
        public rdPConfirmParkingOperationResponse() {
        }
        
        public rdPConfirmParkingOperationResponse(string rdPConfirmParkingOperationResult) {
            this.rdPConfirmParkingOperationResult = rdPConfirmParkingOperationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rdPCancelParkingOperation", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class rdPCancelParkingOperationRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public ConsumoServiciosWeb.PxEndpointWCF.ConsolaSoapHeader ConsolaSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long idTicket;
        
        public rdPCancelParkingOperationRequest() {
        }
        
        public rdPCancelParkingOperationRequest(ConsumoServiciosWeb.PxEndpointWCF.ConsolaSoapHeader ConsolaSoapHeader, long idTicket) {
            this.ConsolaSoapHeader = ConsolaSoapHeader;
            this.idTicket = idTicket;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rdPCancelParkingOperationResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class rdPCancelParkingOperationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool rdPCancelParkingOperationResult;
        
        public rdPCancelParkingOperationResponse() {
        }
        
        public rdPCancelParkingOperationResponse(bool rdPCancelParkingOperationResult) {
            this.rdPCancelParkingOperationResult = rdPCancelParkingOperationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEndpointsChannel : ConsumoServiciosWeb.PxEndpointWCF.IEndpoints, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EndpointsClient : System.ServiceModel.ClientBase<ConsumoServiciosWeb.PxEndpointWCF.IEndpoints>, ConsumoServiciosWeb.PxEndpointWCF.IEndpoints {
        
        public EndpointsClient() {
        }
        
        public EndpointsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EndpointsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EndpointsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EndpointsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmUnParkingOperationResponse ConsumoServiciosWeb.PxEndpointWCF.IEndpoints.rdPConfirmUnParkingOperation(ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmUnParkingOperationRequest request) {
            return base.Channel.rdPConfirmUnParkingOperation(request);
        }
        
        public string rdPConfirmUnParkingOperation(ConsumoServiciosWeb.PxEndpointWCF.ConsolaSoapHeader ConsolaSoapHeader, string xmlIn) {
            ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmUnParkingOperationRequest inValue = new ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmUnParkingOperationRequest();
            inValue.ConsolaSoapHeader = ConsolaSoapHeader;
            inValue.xmlIn = xmlIn;
            ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmUnParkingOperationResponse retVal = ((ConsumoServiciosWeb.PxEndpointWCF.IEndpoints)(this)).rdPConfirmUnParkingOperation(inValue);
            return retVal.rdPConfirmUnParkingOperationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmUnParkingOperationResponse> ConsumoServiciosWeb.PxEndpointWCF.IEndpoints.rdPConfirmUnParkingOperationAsync(ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmUnParkingOperationRequest request) {
            return base.Channel.rdPConfirmUnParkingOperationAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmUnParkingOperationResponse> rdPConfirmUnParkingOperationAsync(ConsumoServiciosWeb.PxEndpointWCF.ConsolaSoapHeader ConsolaSoapHeader, string xmlIn) {
            ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmUnParkingOperationRequest inValue = new ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmUnParkingOperationRequest();
            inValue.ConsolaSoapHeader = ConsolaSoapHeader;
            inValue.xmlIn = xmlIn;
            return ((ConsumoServiciosWeb.PxEndpointWCF.IEndpoints)(this)).rdPConfirmUnParkingOperationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoServiciosWeb.PxEndpointWCF.rdPQueryFinePaymentQuantityResponse ConsumoServiciosWeb.PxEndpointWCF.IEndpoints.rdPQueryFinePaymentQuantity(ConsumoServiciosWeb.PxEndpointWCF.rdPQueryFinePaymentQuantityRequest request) {
            return base.Channel.rdPQueryFinePaymentQuantity(request);
        }
        
        public string rdPQueryFinePaymentQuantity(ConsumoServiciosWeb.PxEndpointWCF.ConsolaSoapHeader ConsolaSoapHeader, string xmlIn) {
            ConsumoServiciosWeb.PxEndpointWCF.rdPQueryFinePaymentQuantityRequest inValue = new ConsumoServiciosWeb.PxEndpointWCF.rdPQueryFinePaymentQuantityRequest();
            inValue.ConsolaSoapHeader = ConsolaSoapHeader;
            inValue.xmlIn = xmlIn;
            ConsumoServiciosWeb.PxEndpointWCF.rdPQueryFinePaymentQuantityResponse retVal = ((ConsumoServiciosWeb.PxEndpointWCF.IEndpoints)(this)).rdPQueryFinePaymentQuantity(inValue);
            return retVal.rdPQueryFinePaymentQuantityResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumoServiciosWeb.PxEndpointWCF.rdPQueryFinePaymentQuantityResponse> ConsumoServiciosWeb.PxEndpointWCF.IEndpoints.rdPQueryFinePaymentQuantityAsync(ConsumoServiciosWeb.PxEndpointWCF.rdPQueryFinePaymentQuantityRequest request) {
            return base.Channel.rdPQueryFinePaymentQuantityAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumoServiciosWeb.PxEndpointWCF.rdPQueryFinePaymentQuantityResponse> rdPQueryFinePaymentQuantityAsync(ConsumoServiciosWeb.PxEndpointWCF.ConsolaSoapHeader ConsolaSoapHeader, string xmlIn) {
            ConsumoServiciosWeb.PxEndpointWCF.rdPQueryFinePaymentQuantityRequest inValue = new ConsumoServiciosWeb.PxEndpointWCF.rdPQueryFinePaymentQuantityRequest();
            inValue.ConsolaSoapHeader = ConsolaSoapHeader;
            inValue.xmlIn = xmlIn;
            return ((ConsumoServiciosWeb.PxEndpointWCF.IEndpoints)(this)).rdPQueryFinePaymentQuantityAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoServiciosWeb.PxEndpointWCF.rdPQueryListOfFinesResponse ConsumoServiciosWeb.PxEndpointWCF.IEndpoints.rdPQueryListOfFines(ConsumoServiciosWeb.PxEndpointWCF.rdPQueryListOfFinesRequest request) {
            return base.Channel.rdPQueryListOfFines(request);
        }
        
        public string rdPQueryListOfFines(ConsumoServiciosWeb.PxEndpointWCF.ConsolaSoapHeader ConsolaSoapHeader, string xmlIn) {
            ConsumoServiciosWeb.PxEndpointWCF.rdPQueryListOfFinesRequest inValue = new ConsumoServiciosWeb.PxEndpointWCF.rdPQueryListOfFinesRequest();
            inValue.ConsolaSoapHeader = ConsolaSoapHeader;
            inValue.xmlIn = xmlIn;
            ConsumoServiciosWeb.PxEndpointWCF.rdPQueryListOfFinesResponse retVal = ((ConsumoServiciosWeb.PxEndpointWCF.IEndpoints)(this)).rdPQueryListOfFines(inValue);
            return retVal.rdPQueryListOfFinesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumoServiciosWeb.PxEndpointWCF.rdPQueryListOfFinesResponse> ConsumoServiciosWeb.PxEndpointWCF.IEndpoints.rdPQueryListOfFinesAsync(ConsumoServiciosWeb.PxEndpointWCF.rdPQueryListOfFinesRequest request) {
            return base.Channel.rdPQueryListOfFinesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumoServiciosWeb.PxEndpointWCF.rdPQueryListOfFinesResponse> rdPQueryListOfFinesAsync(ConsumoServiciosWeb.PxEndpointWCF.ConsolaSoapHeader ConsolaSoapHeader, string xmlIn) {
            ConsumoServiciosWeb.PxEndpointWCF.rdPQueryListOfFinesRequest inValue = new ConsumoServiciosWeb.PxEndpointWCF.rdPQueryListOfFinesRequest();
            inValue.ConsolaSoapHeader = ConsolaSoapHeader;
            inValue.xmlIn = xmlIn;
            return ((ConsumoServiciosWeb.PxEndpointWCF.IEndpoints)(this)).rdPQueryListOfFinesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmFinePaymentResponse ConsumoServiciosWeb.PxEndpointWCF.IEndpoints.rdPConfirmFinePayment(ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmFinePaymentRequest request) {
            return base.Channel.rdPConfirmFinePayment(request);
        }
        
        public string rdPConfirmFinePayment(ConsumoServiciosWeb.PxEndpointWCF.ConsolaSoapHeader ConsolaSoapHeader, string xmlIn) {
            ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmFinePaymentRequest inValue = new ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmFinePaymentRequest();
            inValue.ConsolaSoapHeader = ConsolaSoapHeader;
            inValue.xmlIn = xmlIn;
            ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmFinePaymentResponse retVal = ((ConsumoServiciosWeb.PxEndpointWCF.IEndpoints)(this)).rdPConfirmFinePayment(inValue);
            return retVal.rdPConfirmFinePaymentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmFinePaymentResponse> ConsumoServiciosWeb.PxEndpointWCF.IEndpoints.rdPConfirmFinePaymentAsync(ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmFinePaymentRequest request) {
            return base.Channel.rdPConfirmFinePaymentAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmFinePaymentResponse> rdPConfirmFinePaymentAsync(ConsumoServiciosWeb.PxEndpointWCF.ConsolaSoapHeader ConsolaSoapHeader, string xmlIn) {
            ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmFinePaymentRequest inValue = new ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmFinePaymentRequest();
            inValue.ConsolaSoapHeader = ConsolaSoapHeader;
            inValue.xmlIn = xmlIn;
            return ((ConsumoServiciosWeb.PxEndpointWCF.IEndpoints)(this)).rdPConfirmFinePaymentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoServiciosWeb.PxEndpointWCF.rdPNotifyAlarmResponse ConsumoServiciosWeb.PxEndpointWCF.IEndpoints.rdPNotifyAlarm(ConsumoServiciosWeb.PxEndpointWCF.rdPNotifyAlarmRequest request) {
            return base.Channel.rdPNotifyAlarm(request);
        }
        
        public string rdPNotifyAlarm(ConsumoServiciosWeb.PxEndpointWCF.ConsolaSoapHeader ConsolaSoapHeader, string xmlIn) {
            ConsumoServiciosWeb.PxEndpointWCF.rdPNotifyAlarmRequest inValue = new ConsumoServiciosWeb.PxEndpointWCF.rdPNotifyAlarmRequest();
            inValue.ConsolaSoapHeader = ConsolaSoapHeader;
            inValue.xmlIn = xmlIn;
            ConsumoServiciosWeb.PxEndpointWCF.rdPNotifyAlarmResponse retVal = ((ConsumoServiciosWeb.PxEndpointWCF.IEndpoints)(this)).rdPNotifyAlarm(inValue);
            return retVal.rdPNotifyAlarmResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumoServiciosWeb.PxEndpointWCF.rdPNotifyAlarmResponse> ConsumoServiciosWeb.PxEndpointWCF.IEndpoints.rdPNotifyAlarmAsync(ConsumoServiciosWeb.PxEndpointWCF.rdPNotifyAlarmRequest request) {
            return base.Channel.rdPNotifyAlarmAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumoServiciosWeb.PxEndpointWCF.rdPNotifyAlarmResponse> rdPNotifyAlarmAsync(ConsumoServiciosWeb.PxEndpointWCF.ConsolaSoapHeader ConsolaSoapHeader, string xmlIn) {
            ConsumoServiciosWeb.PxEndpointWCF.rdPNotifyAlarmRequest inValue = new ConsumoServiciosWeb.PxEndpointWCF.rdPNotifyAlarmRequest();
            inValue.ConsolaSoapHeader = ConsolaSoapHeader;
            inValue.xmlIn = xmlIn;
            return ((ConsumoServiciosWeb.PxEndpointWCF.IEndpoints)(this)).rdPNotifyAlarmAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoServiciosWeb.PxEndpointWCF.rdPNotifyCollectionResponse ConsumoServiciosWeb.PxEndpointWCF.IEndpoints.rdPNotifyCollection(ConsumoServiciosWeb.PxEndpointWCF.rdPNotifyCollectionRequest request) {
            return base.Channel.rdPNotifyCollection(request);
        }
        
        public string rdPNotifyCollection(ConsumoServiciosWeb.PxEndpointWCF.ConsolaSoapHeader ConsolaSoapHeader, string xmlIn) {
            ConsumoServiciosWeb.PxEndpointWCF.rdPNotifyCollectionRequest inValue = new ConsumoServiciosWeb.PxEndpointWCF.rdPNotifyCollectionRequest();
            inValue.ConsolaSoapHeader = ConsolaSoapHeader;
            inValue.xmlIn = xmlIn;
            ConsumoServiciosWeb.PxEndpointWCF.rdPNotifyCollectionResponse retVal = ((ConsumoServiciosWeb.PxEndpointWCF.IEndpoints)(this)).rdPNotifyCollection(inValue);
            return retVal.rdPNotifyCollectionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumoServiciosWeb.PxEndpointWCF.rdPNotifyCollectionResponse> ConsumoServiciosWeb.PxEndpointWCF.IEndpoints.rdPNotifyCollectionAsync(ConsumoServiciosWeb.PxEndpointWCF.rdPNotifyCollectionRequest request) {
            return base.Channel.rdPNotifyCollectionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumoServiciosWeb.PxEndpointWCF.rdPNotifyCollectionResponse> rdPNotifyCollectionAsync(ConsumoServiciosWeb.PxEndpointWCF.ConsolaSoapHeader ConsolaSoapHeader, string xmlIn) {
            ConsumoServiciosWeb.PxEndpointWCF.rdPNotifyCollectionRequest inValue = new ConsumoServiciosWeb.PxEndpointWCF.rdPNotifyCollectionRequest();
            inValue.ConsolaSoapHeader = ConsolaSoapHeader;
            inValue.xmlIn = xmlIn;
            return ((ConsumoServiciosWeb.PxEndpointWCF.IEndpoints)(this)).rdPNotifyCollectionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmParkingOperationResponse ConsumoServiciosWeb.PxEndpointWCF.IEndpoints.rdPConfirmParkingOperation(ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmParkingOperationRequest request) {
            return base.Channel.rdPConfirmParkingOperation(request);
        }
        
        public string rdPConfirmParkingOperation(ConsumoServiciosWeb.PxEndpointWCF.ConsolaSoapHeader ConsolaSoapHeader, string xmlIn) {
            ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmParkingOperationRequest inValue = new ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmParkingOperationRequest();
            inValue.ConsolaSoapHeader = ConsolaSoapHeader;
            inValue.xmlIn = xmlIn;
            ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmParkingOperationResponse retVal = ((ConsumoServiciosWeb.PxEndpointWCF.IEndpoints)(this)).rdPConfirmParkingOperation(inValue);
            return retVal.rdPConfirmParkingOperationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmParkingOperationResponse> ConsumoServiciosWeb.PxEndpointWCF.IEndpoints.rdPConfirmParkingOperationAsync(ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmParkingOperationRequest request) {
            return base.Channel.rdPConfirmParkingOperationAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmParkingOperationResponse> rdPConfirmParkingOperationAsync(ConsumoServiciosWeb.PxEndpointWCF.ConsolaSoapHeader ConsolaSoapHeader, string xmlIn) {
            ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmParkingOperationRequest inValue = new ConsumoServiciosWeb.PxEndpointWCF.rdPConfirmParkingOperationRequest();
            inValue.ConsolaSoapHeader = ConsolaSoapHeader;
            inValue.xmlIn = xmlIn;
            return ((ConsumoServiciosWeb.PxEndpointWCF.IEndpoints)(this)).rdPConfirmParkingOperationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoServiciosWeb.PxEndpointWCF.rdPCancelParkingOperationResponse ConsumoServiciosWeb.PxEndpointWCF.IEndpoints.rdPCancelParkingOperation(ConsumoServiciosWeb.PxEndpointWCF.rdPCancelParkingOperationRequest request) {
            return base.Channel.rdPCancelParkingOperation(request);
        }
        
        public bool rdPCancelParkingOperation(ConsumoServiciosWeb.PxEndpointWCF.ConsolaSoapHeader ConsolaSoapHeader, long idTicket) {
            ConsumoServiciosWeb.PxEndpointWCF.rdPCancelParkingOperationRequest inValue = new ConsumoServiciosWeb.PxEndpointWCF.rdPCancelParkingOperationRequest();
            inValue.ConsolaSoapHeader = ConsolaSoapHeader;
            inValue.idTicket = idTicket;
            ConsumoServiciosWeb.PxEndpointWCF.rdPCancelParkingOperationResponse retVal = ((ConsumoServiciosWeb.PxEndpointWCF.IEndpoints)(this)).rdPCancelParkingOperation(inValue);
            return retVal.rdPCancelParkingOperationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumoServiciosWeb.PxEndpointWCF.rdPCancelParkingOperationResponse> ConsumoServiciosWeb.PxEndpointWCF.IEndpoints.rdPCancelParkingOperationAsync(ConsumoServiciosWeb.PxEndpointWCF.rdPCancelParkingOperationRequest request) {
            return base.Channel.rdPCancelParkingOperationAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumoServiciosWeb.PxEndpointWCF.rdPCancelParkingOperationResponse> rdPCancelParkingOperationAsync(ConsumoServiciosWeb.PxEndpointWCF.ConsolaSoapHeader ConsolaSoapHeader, long idTicket) {
            ConsumoServiciosWeb.PxEndpointWCF.rdPCancelParkingOperationRequest inValue = new ConsumoServiciosWeb.PxEndpointWCF.rdPCancelParkingOperationRequest();
            inValue.ConsolaSoapHeader = ConsolaSoapHeader;
            inValue.idTicket = idTicket;
            return ((ConsumoServiciosWeb.PxEndpointWCF.IEndpoints)(this)).rdPCancelParkingOperationAsync(inValue);
        }
    }
}
