//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumoServiciosWeb.integraExternalServicesRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="integraExternalServicesRef.integraExternalServicesSoap")]
    public interface integraExternalServicesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NotifyPlateFine", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string NotifyPlateFine(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NotifyPlateFine", ReplyAction="*")]
        System.Threading.Tasks.Task<string> NotifyPlateFineAsync(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NotifyPlateFineJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string NotifyPlateFineJSON(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NotifyPlateFineJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<string> NotifyPlateFineJSONAsync(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NotifyPlateParking", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string NotifyPlateParking(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NotifyPlateParking", ReplyAction="*")]
        System.Threading.Tasks.Task<string> NotifyPlateParkingAsync(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NotifyPlateParkingJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string NotifyPlateParkingJSON(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NotifyPlateParkingJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<string> NotifyPlateParkingJSONAsync(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryPlateLastParkingOperation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string QueryPlateLastParkingOperation(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryPlateLastParkingOperation", ReplyAction="*")]
        System.Threading.Tasks.Task<string> QueryPlateLastParkingOperationAsync(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryPlateLastParkingOperationJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string QueryPlateLastParkingOperationJSON(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryPlateLastParkingOperationJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<string> QueryPlateLastParkingOperationJSONAsync(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryParkingOperations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string QueryParkingOperations(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryParkingOperations", ReplyAction="*")]
        System.Threading.Tasks.Task<string> QueryParkingOperationsAsync(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryParkingOperationsJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string QueryParkingOperationsJSON(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryParkingOperationsJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<string> QueryParkingOperationsJSONAsync(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryFinePayments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string QueryFinePayments(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryFinePayments", ReplyAction="*")]
        System.Threading.Tasks.Task<string> QueryFinePaymentsAsync(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryFinePaymentsJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string QueryFinePaymentsJSON(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryFinePaymentsJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<string> QueryFinePaymentsJSONAsync(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryCoupon", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string QueryCoupon(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryCoupon", ReplyAction="*")]
        System.Threading.Tasks.Task<string> QueryCouponAsync(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryCouponJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string QueryCouponJSON(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryCouponJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<string> QueryCouponJSONAsync(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConfirmCoupon", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ConfirmCoupon(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConfirmCoupon", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ConfirmCouponAsync(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConfirmCouponJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ConfirmCouponJSON(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConfirmCouponJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ConfirmCouponJSONAsync(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NotifyCarEntry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string NotifyCarEntry(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NotifyCarEntry", ReplyAction="*")]
        System.Threading.Tasks.Task<string> NotifyCarEntryAsync(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NotifyCarEntryJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string NotifyCarEntryJSON(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NotifyCarEntryJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<string> NotifyCarEntryJSONAsync(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TryCarPayment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string TryCarPayment(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TryCarPayment", ReplyAction="*")]
        System.Threading.Tasks.Task<string> TryCarPaymentAsync(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TryCarPaymentJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string TryCarPaymentJSON(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TryCarPaymentJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<string> TryCarPaymentJSONAsync(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NotifyCarExit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string NotifyCarExit(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NotifyCarExit", ReplyAction="*")]
        System.Threading.Tasks.Task<string> NotifyCarExitAsync(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NotifyCarExitJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string NotifyCarExitJSON(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NotifyCarExitJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<string> NotifyCarExitJSONAsync(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendPushWPNotificationsTo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SendPushWPNotificationsTo(string strUser, string strToastText1, string strToastText2, string strToastParam, string strTileTitle, int iTileCount, string strBackgroundImage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendPushWPNotificationsTo", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> SendPushWPNotificationsToAsync(string strUser, string strToastText1, string strToastText2, string strToastParam, string strTileTitle, int iTileCount, string strBackgroundImage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NotifyTollPayment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string NotifyTollPayment(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NotifyTollPayment", ReplyAction="*")]
        System.Threading.Tasks.Task<string> NotifyTollPaymentAsync(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NotifyTollPaymentJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string NotifyTollPaymentJSON(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NotifyTollPaymentJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<string> NotifyTollPaymentJSONAsync(string jsonIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendPushAndroidNotificationsTo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SendPushAndroidNotificationsTo(string strUser, string strAndroidRawData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendPushAndroidNotificationsTo", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> SendPushAndroidNotificationsToAsync(string strUser, string strAndroidRawData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryFinePaymentQuantity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string QueryFinePaymentQuantity(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryFinePaymentQuantity", ReplyAction="*")]
        System.Threading.Tasks.Task<string> QueryFinePaymentQuantityAsync(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExternalticketPaymentParkingmeter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ExternalticketPaymentParkingmeter(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExternalticketPaymentParkingmeter", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ExternalticketPaymentParkingmeterAsync(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryParkingOperationWithAmountSteps", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string QueryParkingOperationWithAmountSteps(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryParkingOperationWithAmountSteps", ReplyAction="*")]
        System.Threading.Tasks.Task<string> QueryParkingOperationWithAmountStepsAsync(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryUnParkingOperation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string QueryUnParkingOperation(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryUnParkingOperation", ReplyAction="*")]
        System.Threading.Tasks.Task<string> QueryUnParkingOperationAsync(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertExternalParkingOperationInstallationTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertExternalParkingOperationInstallationTime(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertExternalParkingOperationInstallationTime", ReplyAction="*")]
        System.Threading.Tasks.Task<string> InsertExternalParkingOperationInstallationTimeAsync(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertExternalUnParkingOperationInstallationTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertExternalUnParkingOperationInstallationTime(string xmlIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertExternalUnParkingOperationInstallationTime", ReplyAction="*")]
        System.Threading.Tasks.Task<string> InsertExternalUnParkingOperationInstallationTimeAsync(string xmlIn);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface integraExternalServicesSoapChannel : ConsumoServiciosWeb.integraExternalServicesRef.integraExternalServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class integraExternalServicesSoapClient : System.ServiceModel.ClientBase<ConsumoServiciosWeb.integraExternalServicesRef.integraExternalServicesSoap>, ConsumoServiciosWeb.integraExternalServicesRef.integraExternalServicesSoap {
        
        public integraExternalServicesSoapClient() {
        }
        
        public integraExternalServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public integraExternalServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public integraExternalServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public integraExternalServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string NotifyPlateFine(string xmlIn) {
            return base.Channel.NotifyPlateFine(xmlIn);
        }
        
        public System.Threading.Tasks.Task<string> NotifyPlateFineAsync(string xmlIn) {
            return base.Channel.NotifyPlateFineAsync(xmlIn);
        }
        
        public string NotifyPlateFineJSON(string jsonIn) {
            return base.Channel.NotifyPlateFineJSON(jsonIn);
        }
        
        public System.Threading.Tasks.Task<string> NotifyPlateFineJSONAsync(string jsonIn) {
            return base.Channel.NotifyPlateFineJSONAsync(jsonIn);
        }
        
        public string NotifyPlateParking(string xmlIn) {
            return base.Channel.NotifyPlateParking(xmlIn);
        }
        
        public System.Threading.Tasks.Task<string> NotifyPlateParkingAsync(string xmlIn) {
            return base.Channel.NotifyPlateParkingAsync(xmlIn);
        }
        
        public string NotifyPlateParkingJSON(string jsonIn) {
            return base.Channel.NotifyPlateParkingJSON(jsonIn);
        }
        
        public System.Threading.Tasks.Task<string> NotifyPlateParkingJSONAsync(string jsonIn) {
            return base.Channel.NotifyPlateParkingJSONAsync(jsonIn);
        }
        
        public string QueryPlateLastParkingOperation(string xmlIn) {
            return base.Channel.QueryPlateLastParkingOperation(xmlIn);
        }
        
        public System.Threading.Tasks.Task<string> QueryPlateLastParkingOperationAsync(string xmlIn) {
            return base.Channel.QueryPlateLastParkingOperationAsync(xmlIn);
        }
        
        public string QueryPlateLastParkingOperationJSON(string jsonIn) {
            return base.Channel.QueryPlateLastParkingOperationJSON(jsonIn);
        }
        
        public System.Threading.Tasks.Task<string> QueryPlateLastParkingOperationJSONAsync(string jsonIn) {
            return base.Channel.QueryPlateLastParkingOperationJSONAsync(jsonIn);
        }
        
        public string QueryParkingOperations(string xmlIn) {
            return base.Channel.QueryParkingOperations(xmlIn);
        }
        
        public System.Threading.Tasks.Task<string> QueryParkingOperationsAsync(string xmlIn) {
            return base.Channel.QueryParkingOperationsAsync(xmlIn);
        }
        
        public string QueryParkingOperationsJSON(string jsonIn) {
            return base.Channel.QueryParkingOperationsJSON(jsonIn);
        }
        
        public System.Threading.Tasks.Task<string> QueryParkingOperationsJSONAsync(string jsonIn) {
            return base.Channel.QueryParkingOperationsJSONAsync(jsonIn);
        }
        
        public string QueryFinePayments(string xmlIn) {
            return base.Channel.QueryFinePayments(xmlIn);
        }
        
        public System.Threading.Tasks.Task<string> QueryFinePaymentsAsync(string xmlIn) {
            return base.Channel.QueryFinePaymentsAsync(xmlIn);
        }
        
        public string QueryFinePaymentsJSON(string jsonIn) {
            return base.Channel.QueryFinePaymentsJSON(jsonIn);
        }
        
        public System.Threading.Tasks.Task<string> QueryFinePaymentsJSONAsync(string jsonIn) {
            return base.Channel.QueryFinePaymentsJSONAsync(jsonIn);
        }
        
        public string QueryCoupon(string xmlIn) {
            return base.Channel.QueryCoupon(xmlIn);
        }
        
        public System.Threading.Tasks.Task<string> QueryCouponAsync(string xmlIn) {
            return base.Channel.QueryCouponAsync(xmlIn);
        }
        
        public string QueryCouponJSON(string jsonIn) {
            return base.Channel.QueryCouponJSON(jsonIn);
        }
        
        public System.Threading.Tasks.Task<string> QueryCouponJSONAsync(string jsonIn) {
            return base.Channel.QueryCouponJSONAsync(jsonIn);
        }
        
        public string ConfirmCoupon(string xmlIn) {
            return base.Channel.ConfirmCoupon(xmlIn);
        }
        
        public System.Threading.Tasks.Task<string> ConfirmCouponAsync(string xmlIn) {
            return base.Channel.ConfirmCouponAsync(xmlIn);
        }
        
        public string ConfirmCouponJSON(string jsonIn) {
            return base.Channel.ConfirmCouponJSON(jsonIn);
        }
        
        public System.Threading.Tasks.Task<string> ConfirmCouponJSONAsync(string jsonIn) {
            return base.Channel.ConfirmCouponJSONAsync(jsonIn);
        }
        
        public string NotifyCarEntry(string xmlIn) {
            return base.Channel.NotifyCarEntry(xmlIn);
        }
        
        public System.Threading.Tasks.Task<string> NotifyCarEntryAsync(string xmlIn) {
            return base.Channel.NotifyCarEntryAsync(xmlIn);
        }
        
        public string NotifyCarEntryJSON(string jsonIn) {
            return base.Channel.NotifyCarEntryJSON(jsonIn);
        }
        
        public System.Threading.Tasks.Task<string> NotifyCarEntryJSONAsync(string jsonIn) {
            return base.Channel.NotifyCarEntryJSONAsync(jsonIn);
        }
        
        public string TryCarPayment(string xmlIn) {
            return base.Channel.TryCarPayment(xmlIn);
        }
        
        public System.Threading.Tasks.Task<string> TryCarPaymentAsync(string xmlIn) {
            return base.Channel.TryCarPaymentAsync(xmlIn);
        }
        
        public string TryCarPaymentJSON(string jsonIn) {
            return base.Channel.TryCarPaymentJSON(jsonIn);
        }
        
        public System.Threading.Tasks.Task<string> TryCarPaymentJSONAsync(string jsonIn) {
            return base.Channel.TryCarPaymentJSONAsync(jsonIn);
        }
        
        public string NotifyCarExit(string xmlIn) {
            return base.Channel.NotifyCarExit(xmlIn);
        }
        
        public System.Threading.Tasks.Task<string> NotifyCarExitAsync(string xmlIn) {
            return base.Channel.NotifyCarExitAsync(xmlIn);
        }
        
        public string NotifyCarExitJSON(string jsonIn) {
            return base.Channel.NotifyCarExitJSON(jsonIn);
        }
        
        public System.Threading.Tasks.Task<string> NotifyCarExitJSONAsync(string jsonIn) {
            return base.Channel.NotifyCarExitJSONAsync(jsonIn);
        }
        
        public bool SendPushWPNotificationsTo(string strUser, string strToastText1, string strToastText2, string strToastParam, string strTileTitle, int iTileCount, string strBackgroundImage) {
            return base.Channel.SendPushWPNotificationsTo(strUser, strToastText1, strToastText2, strToastParam, strTileTitle, iTileCount, strBackgroundImage);
        }
        
        public System.Threading.Tasks.Task<bool> SendPushWPNotificationsToAsync(string strUser, string strToastText1, string strToastText2, string strToastParam, string strTileTitle, int iTileCount, string strBackgroundImage) {
            return base.Channel.SendPushWPNotificationsToAsync(strUser, strToastText1, strToastText2, strToastParam, strTileTitle, iTileCount, strBackgroundImage);
        }
        
        public string NotifyTollPayment(string xmlIn) {
            return base.Channel.NotifyTollPayment(xmlIn);
        }
        
        public System.Threading.Tasks.Task<string> NotifyTollPaymentAsync(string xmlIn) {
            return base.Channel.NotifyTollPaymentAsync(xmlIn);
        }
        
        public string NotifyTollPaymentJSON(string jsonIn) {
            return base.Channel.NotifyTollPaymentJSON(jsonIn);
        }
        
        public System.Threading.Tasks.Task<string> NotifyTollPaymentJSONAsync(string jsonIn) {
            return base.Channel.NotifyTollPaymentJSONAsync(jsonIn);
        }
        
        public bool SendPushAndroidNotificationsTo(string strUser, string strAndroidRawData) {
            return base.Channel.SendPushAndroidNotificationsTo(strUser, strAndroidRawData);
        }
        
        public System.Threading.Tasks.Task<bool> SendPushAndroidNotificationsToAsync(string strUser, string strAndroidRawData) {
            return base.Channel.SendPushAndroidNotificationsToAsync(strUser, strAndroidRawData);
        }
        
        public string QueryFinePaymentQuantity(string xmlIn) {
            return base.Channel.QueryFinePaymentQuantity(xmlIn);
        }
        
        public System.Threading.Tasks.Task<string> QueryFinePaymentQuantityAsync(string xmlIn) {
            return base.Channel.QueryFinePaymentQuantityAsync(xmlIn);
        }
        
        public string ExternalticketPaymentParkingmeter(string xmlIn) {
            return base.Channel.ExternalticketPaymentParkingmeter(xmlIn);
        }
        
        public System.Threading.Tasks.Task<string> ExternalticketPaymentParkingmeterAsync(string xmlIn) {
            return base.Channel.ExternalticketPaymentParkingmeterAsync(xmlIn);
        }
        
        public string QueryParkingOperationWithAmountSteps(string xmlIn) {
            return base.Channel.QueryParkingOperationWithAmountSteps(xmlIn);
        }
        
        public System.Threading.Tasks.Task<string> QueryParkingOperationWithAmountStepsAsync(string xmlIn) {
            return base.Channel.QueryParkingOperationWithAmountStepsAsync(xmlIn);
        }
        
        public string QueryUnParkingOperation(string xmlIn) {
            return base.Channel.QueryUnParkingOperation(xmlIn);
        }
        
        public System.Threading.Tasks.Task<string> QueryUnParkingOperationAsync(string xmlIn) {
            return base.Channel.QueryUnParkingOperationAsync(xmlIn);
        }
        
        public string InsertExternalParkingOperationInstallationTime(string xmlIn) {
            return base.Channel.InsertExternalParkingOperationInstallationTime(xmlIn);
        }
        
        public System.Threading.Tasks.Task<string> InsertExternalParkingOperationInstallationTimeAsync(string xmlIn) {
            return base.Channel.InsertExternalParkingOperationInstallationTimeAsync(xmlIn);
        }
        
        public string InsertExternalUnParkingOperationInstallationTime(string xmlIn) {
            return base.Channel.InsertExternalUnParkingOperationInstallationTime(xmlIn);
        }
        
        public System.Threading.Tasks.Task<string> InsertExternalUnParkingOperationInstallationTimeAsync(string xmlIn) {
            return base.Channel.InsertExternalUnParkingOperationInstallationTimeAsync(xmlIn);
        }
    }
}
